apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      securityContext:
        fsGroup: 5984
      containers:
        - name: couchdb
          image: couchdb:3.4
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_SINGLE_NODE
              value: "true"
            - name: NODENAME
              value: "couchdb@127.0.0.1"
          envFrom:
            - secretRef:
                name: couchdb-admin
          volumeMounts:
            - name: data
              mountPath: /opt/couchdb/data
          readinessProbe:
            httpGet:
              path: /
              port: 5984
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5984
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: couchdb-data
