apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quartz
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts: ["notes.davidbor.eu"]
      secretName: cloudflare-origin-tls
  rules:
    - host: davidbor.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quartz
                port:
                  number: 80
